# Generated by Django 2.2.5 on 2019-12-20 00:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0007_auto_20191218_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(to='tomo.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tomo.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 20, 0, 35, 19, 347048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 20, 0, 35, 19, 347048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='hosted_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 20, 0, 35, 19, 347048, tzinfo=utc)),
        ),
    ]
